name: 'Purge cache existing in jsDelivr Network'
author: 'PiQuark6046 and contributors'
description: 'Clone your GitHub repo into jsDelivr Network to enhance transmission speed'

inputs:
  branches:
    description: 'Additional branches whose jsDelivr cache should be purged'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install npm packages
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run program
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        BRANCHES: ${{ inputs.branches }}
        WORKFLOWREF: ${{ github.workflow_ref }}
        CI_WORKSPACE_PATH: ${{ github.workspace }}
      run: npm run ci -- --gh-token "$GITHUB_TOKEN" --repo "$REPO" --workflow-ref "$WORKFLOWREF" --branch "$BRANCHES" --ci-workspace-path "$CI_WORKSPACE_PATH"
      shell: bash
      working-directory: ${{ github.action_path }}
