name: 'Purge cache existing in jsDelivr Network'
author: 'PiQuark6046 and contributors'
description: 'Clone your GitHub repo into jsDelivr Network to enhance transmission speed'

inputs:
  branches:
    description: 'The your branches that you want to purge cache existing in jsDelivr'
    required: false
    default: 'master main'

  delay:
    description: 'A time that delay between GitHub RAW file service and actual git operation'
    required: false
    default: '01:00:00'

runs:
  using: 'composite'
  steps:
    - name: Set up NodeJS LTS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - name: Install npm packages
      run: |
        sudo npm i -g typescript
        npm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Compile Typescript
      run: tsc
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Create env file
      run: |
        touch .env
        echo GITHUB_REPO=${{ github.repository }} >> .env
        echo GITHUB_TOKEN=${{ github.token }} >> .env
        echo GITHUB_WORKFLOW_NAME=${{ github.workflow }} >> .env
        echo INPUT_BRANCHES=${{ inputs.branches }} >> .env
        echo INPUT_DELAY=${{ inputs.delay }} >> .env
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run compiled scripts
      run: node main.js
      shell: bash
      working-directory: ${{ github.action_path }}